version: "3.9"

services:
  postgres:
    image: postgres:13.3
    container_name: test-poster-db
    environment:
      POSTGRES_DB: test_poster
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - 5432:5432