version: "3.9"

services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "db_poster"
      POSTGRES_USER: "pguser"
      POSTGRES_PASSWORD: "pgpwd"
    ports:
      - "5432:5432"