// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Comment struct {
	ID         string    `json:"id"`
	ParentID   *string   `json:"parentId,omitempty"`
	PostID     string    `json:"postId"`
	AuthorID   string    `json:"authorId"`
	Body       string    `json:"body"`
	Login      string    `json:"login"`
	CreateDate time.Time `json:"createDate"`
	UpdDate    time.Time `json:"updDate"`
	Likes      *int      `json:"likes,omitempty"`
	Dislikes   *int      `json:"dislikes,omitempty"`
	Cnt        *int      `json:"cnt,omitempty"`
}

type Mutation struct {
}

type NewCommentInput struct {
	ParentID *string `json:"parentId,omitempty"`
	PostID   string  `json:"postId"`
	AuthorID string  `json:"authorId"`
	Body     string  `json:"body"`
}

type NewCommentLikeInput struct {
	Like      bool   `json:"like"`
	AuthorID  string `json:"authorId"`
	CommentID string `json:"commentId"`
}

type NewPostInput struct {
	Title       string `json:"title"`
	AuthorID    string `json:"authorId"`
	Body        string `json:"body"`
	IsCommented bool   `json:"isCommented"`
}

type NewPostLikeInput struct {
	Like     bool   `json:"like"`
	AuthorID string `json:"authorId"`
	PostID   string `json:"postId"`
}

type NewUserInput struct {
	Login   string `json:"login"`
	Name    string `json:"name"`
	Surname string `json:"surname"`
	Phone   string `json:"phone"`
	Email   string `json:"email"`
}

type Post struct {
	ID          string    `json:"id"`
	Title       string    `json:"title"`
	AuthorID    string    `json:"authorId"`
	Body        string    `json:"body"`
	CreateDate  time.Time `json:"createDate"`
	UpdDate     time.Time `json:"updDate"`
	IsCommented bool      `json:"isCommented"`
	Likes       *int      `json:"likes,omitempty"`
	Dislikes    *int      `json:"dislikes,omitempty"`
}

type Query struct {
}

type Rating struct {
	Likes    int `json:"likes"`
	Dislikes int `json:"dislikes"`
}

type Subscr struct {
	UserID string `json:"userId"`
	PostID string `json:"postId"`
}

type SubscrInput struct {
	UserID string `json:"userId"`
	PostID string `json:"postId"`
}

type Subscription struct {
}

type UpdCommentInput struct {
	ID   string `json:"Id"`
	Body string `json:"body"`
}

type UpdPostInput struct {
	PostID      string  `json:"postId"`
	Title       *string `json:"title,omitempty"`
	Body        *string `json:"body,omitempty"`
	IsCommented *bool   `json:"isCommented,omitempty"`
}

type User struct {
	ID         string    `json:"id"`
	Login      string    `json:"login"`
	CreateDate time.Time `json:"createDate"`
	IsDeleted  bool      `json:"isDeleted"`
	Name       string    `json:"name"`
	Surname    string    `json:"surname"`
	Phone      string    `json:"phone"`
	Email      string    `json:"email"`
	Posts      []*Post   `json:"posts,omitempty"`
}
